apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  namespace: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/ikrar557/karsajobs-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"