# Menentukan versi dari docker-compose, walaupun pada official docs nya sudah 'obselete'
version: '3.7'

# Mendefinisikan semua service atau container yang akan dijalankan oleh docker-compose
services:
# Menjalankan service atau container dengan nama 'item-db'
  item-db:
    # Mengambil image mongodb dari 'Docker Hub' secara eksplisit dengan menambahkan URL 'docker.io'
    image: docker.io/mongo:3
    # Menentukan port yang akan digunakan oleh container
    ports:
      - 27017:27017
    # Menggunakan 'persistent volume' bernama 'app-db' dengan target '/data/db' di dalam container
    volumes:
      - app-db:/data/db 
    # Menambahkan policy agar container selalu 'restart' ketika berhenti
    restart: always

  # Menjalan service atau container dengan nama 'item-app'
  item-app:
    # Mengambil image 'item-app' yang sebelumnya sudah di push ke Github Packages secara eksplisit
    # Dengan menggunakan URL 'ghcr.io'
    image: ghcr.io/ikrar557/item-app:v1
    # Menginstall dependencies dan menjalankan aplikasi
    command: sh -c "npm install --production --unsafe-perm && npm start"
    # Menentukan 'direktori kerja' pada container 'item-app'
    working_dir: /app
    # Menentukan port yang akan digunakan oleh container
    ports:
      - 80:8080
    # Melakukan bind mount direktori saat ini ke dalam direktori '/app' di container
    volumes:
      - ./:/app
    # Membuat policy agar container 'item-app' berjalan setelah container 'item-db' dapat dijalankan
    depends_on:
      - item-db
    # Menambahkan 'environment' yang akan digunakan oleh container
    environment:
      - NODE_ENV=production
      - DB_HOST=item-db
    # Menambahkan policy agar container selalu 'restart' ketika berhenti
    restart: always

# Berisi block code untuk membuat volumes (bisa lebih dari 1)
volumes:
  # Membuat volume dengan nama 'app-db'
  app-db: