apiVersion: v1      # Versi API Kubernetes yang digunakan
kind: List          # Menentukan jenis resource berupa daftar/list dari beberapa resource
items:             # Daftar item yang akan dibuat
- apiVersion: v1    # Versi API untuk namespace pertama
  kind: Namespace   # Menentukan jenis resource adalah Namespace
  metadata:        # Metadata untuk namespace
    name: deployments    # Nama namespace untuk aplikasi
    labels:             # Label yang diterapkan pada namespace
      app: deployments  # Label app dengan nilai deployments
- apiVersion: v1    # Versi API untuk namespace kedua
  kind: Namespace   # Menentukan jenis resource adalah Namespace
  metadata:        # Metadata untuk namespace
    name: monitoring    # Nama namespace untuk monitoring
    labels:             # Label yang diterapkan pada namespace
      app: monitoring   # Label app dengan nilai monitoring