apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: deployments
    labels:
      app: deployments
- apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring
    labels:
      app: monitoring