apiVersion: apps/v1  # Menentukan versi API yang digunakan
kind: Deployment  # Menentukan resources yang akan dibuat adalah Deployment
metadata:
  name: karsajobs  # Nama Deployment yang digunakan 
  namespace: deployments  # Namespace tempat Deployment ini akan dibuat

spec:
  replicas: 1  # Menentukan jumlah pod yang akan dijalankan
  selector:
    matchLabels:
      app: karsajobs  # Memilih pod dengan label ini
  template:  # Template yang digunakan untuk membuat pod
    metadata:
      labels:
        app: karsajobs  # Label yang diberikan ke pod
    spec:
      containers:
      - name: karsajobs  # Nama container 
        image: ghcr.io/ikrar557/karsajobs:latest  # Image container yang digunakan
        imagePullPolicy: IfNotPresent  # Menentukan imagePullPolicy dimana image akan di-'pull' jika tidak terdapat pada local
        ports:
        - containerPort: 8080  # Port yang digunakan dalam container

        env:  # Daftar environment variables yang digunakan dalam container
        - name: APP_PORT
          value: "8080"  # Menentukan port aplikasi yang akan digunakan
        - name: MONGO_HOST
          value: "mongodb-service"  # Menentukan host database MongoDB
        - name: MONGO_DB
          value: "karsajobs"  # Nama database yang digunakan dalam MongoDB
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret  # Mengambil username MongoDB dari Secret Kubernetes (mongo-secret.yml)
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret  # Mengambil password MongoDB dari Secret Kubernetes (mongo-secret.yml)
              key: MONGO_ROOT_PASSWORD

        resources:  # Menentukan limit dan request resources CPU dan memori untuk container
          requests:  # Permintaan minimal resources yang digunakan
            memory: "64Mi"  # Minimal 64MiB memori
            cpu: "250m"  # Minimal 250 millicore CPU
          limits:  # Batas maksimal esources yang digunakan
            memory: "128Mi"  # Maksimal 128MiB memori
            cpu: "500m"  # Maksimal 500 millicore CPU
