version: 2.1    # Menentukan versi CircleCI yang digunakan

jobs:    # Mendefinisikan pekerjaan yang akan dijalankan
  lint-dockerfile:    # Membuat job untuk melakukan linting pada Dockerfile
    docker:    # Menentukan image Docker yang digunakan
      - image: ubuntu:latest    # Menggunakan image Ubuntu versi terbaru
    steps:    # Langkah-langkah yang akan dijalankan
      - checkout    # Mengambil kode dari repository
      - run:    # Menjalankan perintah
          name: Install dependencies    # Nama langkah untuk instalasi dependensi
          command: |    # Perintah yang akan dijalankan
            apt-get update    # Memperbarui package list
            apt-get install -y wget    # Menginstall wget
      - run:    # Menjalankan perintah kedua
          name: Install Hadolint    # Nama langkah untuk instalasi Hadolint
          command: |    # Perintah akan yang dijalankan
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64    # Mengunduh Hadolint
            chmod +x /bin/hadolint    # Memberikan izin eksekusi
      - run:    # Menjalankan perintah linting
          name: Lint Dockerfile    # Nama langkah untuk linting
          command: hadolint Dockerfile    # Menjalankan Hadolint pada Dockerfile

  build-app-karsajobs-ui:    # Job untuk membangun dan mendorong image
    docker:    # Menentukan image Docker yang digunakan
      - image: cimg/node:14.21    # Menggunakan image Node.js versi 14.21
    steps:    # Langkah-langkah yang akan dijalankan
      - checkout    # Mengambil kode dari repository
      - setup_remote_docker    # Menyiapkan Docker untuk build
      - run:    # Menjalankan perintah build dan push
          name: Build and Push Image    # Nama langkah untuk build dan push
          command: |    # Perintah yang dijalankan
            docker build -t ghcr.io/${GITHUB_USERNAME}/karsajobs-ui:latest .    # Membangun image Docker
            echo $GITHUB_TOKEN | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin    # Login ke GitHub Container Registry
            docker push ghcr.io/${GITHUB_USERNAME}/karsajobs-ui:latest    # Mendorong image ke registry

workflows:    # Mendefinisikan alur kerja
  version: 2    # Versi workflow
  frontend-pipeline:    # Nama pipeline untuk frontend
    jobs:    # Daftar job yang dijalankan
      - lint-dockerfile    # Menjalankan job lint-dockerfile
      - build-app-karsajobs-ui:    # Menjalankan job build-app-karsajobs-ui
          requires:    # Menentukan ketergantungan
            - lint-dockerfile    # Harus menunggu lint-dockerfile selesai
          context: github-credentials    # Menggunakan kredensial GitHub yang sudah dibuat sebelumnya