apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: ghcr.io/ikrar557/orderservice:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: AMQP_URL
          value: "amqp://user:password@rabbitmq.communications.svc.cluster.local:5672"