# Menentukan versi API Kubernetes untuk Service
apiVersion: v1
# Menentukan jenis resource Kubernetes (Service)
kind: Service
# Metadata untuk Service
metadata:
  # Nama Service
  name: orderservice
  # Namespace untuk service yang dibuat
  namespace: deployments
# Spesifikasi konfigurasi Service
spec:
  # Selektor untuk memilih pod
  selector:
    app: orderservice
  # Konfigurasi port
  ports:
  - # Port Service yang dapat diakses dari dalam cluster
    port: 3000
    # Port target pada pod
    targetPort: 3000
    # Port yang dapat diakses dari luar cluster
    nodePort: 30000
  # Tipe Service 
  type: NodePort