auth:
  username: user
  password: password

service:
  type: NodePort
  ports:
    amqp: 5672
    manager: 15672
  nodePorts:
    amqp: 30672
    manager: 31672

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m