apiVersion: v1      # Versi API Kubernetes yang digunakan
kind: ConfigMap     # Jenis resource untuk menyimpan konfigurasi
metadata:
  name: mongodb-config    # Nama ConfigMap
  namespace: deployments  # Namespace tempat ConfigMap dibuat
data:
  mongo.conf: |          # Konfigurasi MongoDB
# Konfigurasi penyimpanan MongoDB
    storage:
      # Lokasi penyimpanan data MongoDB
      dbPath: /data/db   