apiVersion: v1           # Versi API Kubernetes yang digunakan
kind: PersistentVolume  # Jenis resource untuk penyimpanan persisten
metadata:
  name: mongodb-pv      # Nama PersistentVolume
spec:
  capacity:             # Kapasitas penyimpanan
    storage: 1Gi        # Ukuran penyimpanan di atur 1 Gigabyte
  accessModes:          # Mode akses penyimpanan
    - ReadWriteOnce     # Mengatur akses agar bisa diakses oleh satu node
  hostPath:             # Tipe penyimpanan menggunakan hostPath
    path: /data/mongodb # Lokasi penyimpanan di host
---
apiVersion: v1               # Versi API Kubernetes yang digunakan
kind: PersistentVolumeClaim  # Jenis resource untuk klaim penyimpanan
metadata:
  name: mongodb-pvc          # Nama PersistentVolumeClaim
  namespace: deployments     # Namespace tempat PVC dibuat
spec:
  accessModes:              # Menentukan mode akses yang diminta
    - ReadWriteOnce         # Mengatur akses agar bisa diakses oleh satu node
  resources:                # Menentukan resources yang diminta
    requests:
      storage: 1Gi          # Request penyimpanan 1 Gigabyte