apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=     # 'admin' in base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # 'supersecretpassword' in base64