apiVersion: v1           # Versi API Kubernetes yang digunakan
kind: Secret            # Jenis resource untuk menyimpan data rahasia
metadata:
  name: mongodb-secret   # Nama Secret
  namespace: deployments # Namespace tempat Secret dibuat
type: Opaque            # Tipe Secret yang digunakan
data:                   # Data dalam format base64
  MONGO_ROOT_USERNAME: YWRtaW4=                         # encode "admin" menjadi base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==    # encode "password" menjadi base64